image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Terraform
    command: |
      wget https://releases.hashicorp.com/terraform/0.14.9/terraform_0.14.9_linux_amd64.zip
      unzip terraform_0.14.9_linux_amd64.zip
      chmod +x terraform
      sudo mv terraform /usr/local/bin/
